### ISSUE TITLE
Configure SSL for Nginx

### ISSUE THREAD

**Issue by hazadus** [hazadus/drf-nuxt-bookmarks#23]
Add to `./docker/nginx/default.conf`:
```
    listen 443 ssl;
    # RSA certificate
    ssl_certificate /certs/fullchain1.pem;
    ssl_certificate_key /certs/privkey1.pem;

    # Redirect non-https traffic to https
    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    }
```
**Create separate Nginx configs for prod and dev**.

Add to `docker-compose.yml` (note 443 port mapping and `certs` directory):
```
  nginx:
    container_name: "bkmrks-nginx"
    image: nginx:1.23-alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./backend:/code
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/media:/media
      - ./backend/staticfiles:/staticfiles
      - /etc/letsencrypt/archive/bookmarks.hazadus.ru/:/certs
    depends_on:
      - api
```
